version: 2.1

jobs:
    tests:
        docker:
            - image: cypress/browsers:node12.18.0-chrome83-ff77
        steps:
            - checkout
            - run:
                name: Create cache and configuration directories for the client dependencies
                command: |
                    touch ~/.yarnrc
                    mkdir ~/.yarn
                    mkdir -p ~/.cache/yarn ~/.cache/Cypress
            - restore_cache:
                keys:
                    - yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
                    - yarn-{{ .Environment.CACHE_VERSION }}-
            - run:
                name: Install dependencies
                command: make install
            - save_cache:
                key: yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - run:
                name: Create report directory
                command: mkdir tests/reports
            - run:
                name: Lint CSS/LESS code
                command: make stylelint
            - run:
                name: Lint JavaScript/TypeScript code
                command: make eslint
            - run:
                name: Run TS type checking
                command: make type-check
            - run:
                name: Run unit tests
                command: make unit IO="--ci --reporters=default --reporters=jest-junit"
            - run:
                name: Run business acceptance tests
                command: make acceptance IO="--ci --reporters=default --reporters=jest-junit"
            - run:
                name: Run adapters integration tests
                command: make integration IO="--ci --reporters=default --reporters=jest-junit"
            - run:
                name: Run End to End tests
                command: make end-to-end IO="--headless --reporter mocha-junit-reporter"
            - store_test_results:
                path: tests/reports
            - store_artifacts:
                path: tests/reports
            - store_artifacts:
                path: tests/e2e/screenshots
            - store_artifacts:
                path: tests/e2e/videos

workflows:
    version: 2
    pull_request:
        jobs:
            - tests:
                filters:
                    branches:
                        ignore:
                            - master
