version: 2.1

# Aliases

executor-config: &executor-config
    machine:
        image: ubuntu-1604:202004-01
    environment:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
        HOST_USER_IDS: "1001:1002"

# -----

jobs:
    tests:
        <<: *executor-config
        steps:
            - checkout
            - run:
                name: Pull Docker images
                command: make pull
            - run:
                name: Create cache and configuration directories for the client dependencies
                command: |
                    touch ~/.yarnrc
                    mkdir ~/.yarn
                    mkdir -p ~/.cache/yarn ~/.cache/Cypress
            - restore_cache:
                keys:
                    - yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
                    - yarn-{{ .Environment.CACHE_VERSION }}-
            - run:
                name: Install dependencies
                command: make node_modules
            - save_cache:
                key: yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - run:
                name: Create report directory
                command: mkdir tests/reports
            - run:
                name: Lint CSS/LESS code
                command: make stylelint
            - run:
                name: Lint JavaScript/TypeScript code
                command: make eslint
            - run:
                name: Run TS type checking
                command: make type-check
            - run:
                name: Run unit tests
                command: make unit O="--ci --reporters=default --reporters=jest-junit"
            - run:
                name: Set the project permissions so the "node" user of the Cypress Docker image can access it
                command: sudo chown -R 1000:1000 ~/project  ~/.cache/Cypress
            - run:
                name: Run End to End tests
                command: make end-to-end O="--reporter mocha-junit-reporter"
            - run:
                name: Set back the project permissions so the CircleCI user so the test results and artefact can be used
                command: sudo chown -R 1001:1002 ~/project
            - store_test_results:
                path: tests/reports
            - store_artifacts:
                path: tests/reports
            - store_artifacts:
                path: tests/e2e/screenshots
            - store_artifacts:
                path: tests/e2e/videos

workflows:
    version: 2
    pull_request:
        jobs:
            - tests:
                filters:
                    branches:
                        ignore:
                            - master
