version: 2.1

# Aliases

executor-config: &executor-config
    machine:
        image: ubuntu-1604:202004-01
    environment:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
        HOST_USER_IDS: "1001:1002"

# -----

commands:
    proxy-network:
        description: Create "proxy" Docker network (ignore if it already exists)
        steps:
            - run:
                name: Create "proxy" Docker network (ignore if it already exists)
                command: docker network create proxy || true

# -----

jobs:
    tests:
        <<: *executor-config
        steps:
            - checkout
            - proxy-network
            - run:
                name: Pull Docker images
                command: make pull
            - run:
                name: Create cache and configuration directories for the client dependencies
                command: |
                    touch ~/.yarnrc
                    mkdir ~/.yarn
                    mkdir -p ~/.cache/yarn
            - restore_cache:
                keys:
                    - yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
                    - yarn-{{ .Environment.CACHE_VERSION }}-
            - run:
                name: Install dependencies
                command: make node_modules
            - save_cache:
                key: yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - run:
                name: Create report directory
                command: mkdir tests/reports
            - run:
                name: Lint CSS/LESS code
                command: make stylelint O="--custom-formatter 'node_modules/stylelint-junit-formatter' > tests/reports/stylelint.xml"
            - run:
                name: Lint JavaScript/TypeScript code
                command: make eslint O="--no-fix -f junit > tests/reports/eslint.xml"
            - run:
                name: Run TS type checking
                command: make type-check
            - run:
                name: Run unit tests
                command: make unit O="--ci --reporters=default --reporters=jest-junit"
            - run:
                name: Build production-like Docker images
                command: make prod
            - run:
                name: Run End to End tests
                command: make end-to-end O="--reporter mocha-junit-reporter"
            - store_test_results:
                path: tests/reports
            - store_artifacts:
                path: tests/reports
            - store_artifacts:
                path: tests/e2e/screenshots
            - store_artifacts:
                path: tests/e2e/videos

workflows:
    version: 2
    pull_request:
        jobs:
            - tests:
                filters:
                    branches:
                        ignore:
                            - master
